apiVersion: apps/v1
kind: Deployment
metadata:
  name: dekujeme
  labels:
    app: dekujeme
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dekujeme
  template:
    metadata:
      labels:
        app: dekujeme
    spec:
      containers:
        - name: dekujeme
          image: glubo/dekujeme:latest
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: dekujeme
spec:
  selector:
    app: dekujeme
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: dekujeme
spec:
  rules:
    - host: dekujeme.glubo.cz
      http:
        paths:
          - backend:
              service:
                name: dekujeme
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - dekujeme.glubo.cz
      secretName: dekujeme-cert
